services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cellular-automaton-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:pass@mongo:27017/cellular_automaton?authSource=admin
  mongo:
    image: mongo:5.0
    container_name: cellular-automaton-db
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../trees.json:/docker-entrypoint-initdb.d/trees.json:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongo-express:
    image: mongo-express:1.0
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
volumes:
  mongo_data:
